name: neumorphism_flutter
description: A new Flutter project.
version: 1.0.3+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  url_launcher: ^6.3.0
  flutter_markdown: ^0.6.23
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
